cms:
  resource: '@PhatKoalaCmsBundle/Controller/'
  type: annotation
#  prefix: /foo

core:
  resource: '@PhatKoalaCoreBundle/Controller/'
  type: annotation

dashboard:
  resource: '@PhatKoalaDashboardBundle/Controller/'
  type: annotation

user:
  resource: '@PhatKoalaUserBundle/Controller/'
  type: annotation